# 启动端口
server:
    port: 8083

logging:
    file:
        # 日志输出目录
        name: ./logs/${spring.application.name}.log

# mybatis-plus日志
mybatis-plus:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 选择配置文件
spring:
    application:
      # 应用名
      name: springboot-template

    profiles:
        active: test

    # 将404等错误直接抛出异常处理
    mvc:
        throw-exception-if-no-handler-found: true
    # 取消了资源映射，无法映射静态资源比如html、js、css等文件，如有需要请手动配置WebMvcConfigurer
    resources:
        add-mappings: false
    jackson:
        # 日期格式化
        date-format: yyyy-MM-dd HH:mm:ss