logging:
  # 配置日志输出级别
  level:
    com:
      sport: debug


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    # 数据库账号密码
    username: 'root'
    password: '123456'
    url: jdbc:mysql://localhost:3306/sport?serverTimezone=UTC
  # redis
  redis:
    host: localhost
    port: 6379
    # password: 123456



# swagger开关
springfox:
  documentation:
    enabled: false
    auto-startup: false
    swagger-ui:
      enabled: false

# JWT密钥
jwt:
  secret: sdhgfsbfsdjhgkbdpoger8tuwrqwp
  #JWT存储的请求头
  tokenHeader: Authorization
  #JWT负载中拿到开头，空格别忘了
  tokenHead: Bearer