logging:
  # 配置日志输出级别
  level:
    com:
      szy: debug


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    # 数据库账号密码
    username: 'blue'
    password: '123123'
    url: jdbc:mysql://localhost:3306/blue?serverTimezone=UTC

  cloud:
    nacos:
      # 服务发现配置
      discovery:
        namespace: public
        server-addr: localhost:8848
        # username: nacos
        # password: nacos
        group: app




# dubbo 配置
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    # 注册地址
    address: nacos://localhost:8848
    #        username: nacos
    #        password: 123456
    # 其他参数
    parameters:
      namespace: public
  protocol:
    name: dubbo
    port: 20880


# swagger开关
springfox:
  documentation:
    enabled: false
    auto-startup: false
    swagger-ui:
      enabled: false