logging:
  # 配置日志输出级别
  level:
    com:
      sport: debug


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    # 数据库账号密码
    username: 'root'
    password: '318675'
    url: jdbc:mysql://182.43.88.52:3306/sport?serverTimezone=UTC

  cloud:
    nacos:
      # 服务发现配置
      discovery:
        namespace: public
        server-addr: localhost:8848
        # username: nacos
        # password: nacos
        group: app
  # redis
  redis:
    host: localhost
    port: 6379
    # password: 123456



# swagger开关
springfox:
  documentation:
    enabled: false
    auto-startup: false
    swagger-ui:
      enabled: false